name: Library CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Unit Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Pack
        run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }} --no-build

#      - name: Push to NuGet
#        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
#        run: |
#          dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
